let emailValidator = require('./email');
let good1 = emailValidator("abc@yahoo.com");
console.log(good1);
let good2 = emailValidator("abc-100@yahoo.com");
console.log(good2);
let good3 = emailValidator("abc.100@yahoo.com");
console.log(good3);
let good4 = emailValidator("abc111@abc.com");
console.log(good4);
let good5 = emailValidator("abc-100@abc.net");
console.log(good5);
let good6 = emailValidator("abc.100@abc.com.au");
console.log(good6);
let good7 = emailValidator("abc@1.com");
console.log(good7);
let good8 = emailValidator("abc@gmail.com.com");
console.log(good8);
let good9 = emailValidator("abc+100@gmail.com");
console.log(good9);
console.log("\n");
let err1 = emailValidator("abc");
console.log(err1);
let err2 = emailValidator("abc@.com.my");
console.log(err2);
let err3 = emailValidator("abc123@gmail.a");
console.log(err3);
let err4 = emailValidator("abc123@.com");
console.log(err4);
let err5 = emailValidator("abc123@.com.com");
console.log(err5);
let err6 = emailValidator(".abc@abc.com");
console.log(err6);
let err7 = emailValidator("abc()*@gmail.com");
console.log(err7);
let err8 = emailValidator("abc@%*.com");
console.log(err8);
let err9 = emailValidator("abc..2002@gmail.com");
console.log(err9);
let err10 = emailValidator("abc.@gmail.com");
console.log(err10);
let err11 = emailValidator("abc@abc@gmail.com");
console.log(err11);
let err12 = emailValidator("abc@gmail.com.1a");
console.log(err12);
let err13 = emailValidator("abc@gmail.com.aa.au");
console.log(err13);

